// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbOcFx-aoR5wjI4x5ZaofZXoG2D-z0wE4',
    appId: '1:937131988528:web:4d861796c192cc506ebff5',
    messagingSenderId: '937131988528',
    projectId: 'fasostyle-1bb74',
    authDomain: 'fasostyle-1bb74.firebaseapp.com',
    storageBucket: 'fasostyle-1bb74.firebasestorage.app',
    measurementId: 'G-4VP3H5K4ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0EjTTxLPZVa2FOhEWXYCDbTH_qRmwu0U',
    appId: '1:937131988528:android:bc6780f6a916965d6ebff5',
    messagingSenderId: '937131988528',
    projectId: 'fasostyle-1bb74',
    storageBucket: 'fasostyle-1bb74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCweCjhMOCnEYBaXmZaRKS2MLNBimJjWvs',
    appId: '1:937131988528:ios:c045c326422b9b996ebff5',
    messagingSenderId: '937131988528',
    projectId: 'fasostyle-1bb74',
    storageBucket: 'fasostyle-1bb74.firebasestorage.app',
    iosBundleId: 'com.example.fasoStyle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCweCjhMOCnEYBaXmZaRKS2MLNBimJjWvs',
    appId: '1:937131988528:ios:c045c326422b9b996ebff5',
    messagingSenderId: '937131988528',
    projectId: 'fasostyle-1bb74',
    storageBucket: 'fasostyle-1bb74.firebasestorage.app',
    iosBundleId: 'com.example.fasoStyle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbOcFx-aoR5wjI4x5ZaofZXoG2D-z0wE4',
    appId: '1:937131988528:web:cbbd9e4b0b6f39ee6ebff5',
    messagingSenderId: '937131988528',
    projectId: 'fasostyle-1bb74',
    authDomain: 'fasostyle-1bb74.firebaseapp.com',
    storageBucket: 'fasostyle-1bb74.firebasestorage.app',
    measurementId: 'G-K02Y1MWCZZ',
  );
}
