// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUrG7WsoldXB5feWoqpuVBgAwsTJMcQPk',
    appId: '1:152462835663:web:eb672062eeb3d2bef81cba',
    messagingSenderId: '152462835663',
    projectId: 'elegantstyle-5b186',
    authDomain: 'elegantstyle-5b186.firebaseapp.com',
    storageBucket: 'elegantstyle-5b186.firebasestorage.app',
    measurementId: 'G-X8JBMQ0J0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXri5vskRZ6KEt7T85GJ4safdkpaAyZ9I',
    appId: '1:152462835663:android:95720dd99751d11af81cba',
    messagingSenderId: '152462835663',
    projectId: 'elegantstyle-5b186',
    storageBucket: 'elegantstyle-5b186.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqC1cCi_HcTu8q-yXIrXJw83ZbkkM81i4',
    appId: '1:152462835663:ios:51c1f09e841c5164f81cba',
    messagingSenderId: '152462835663',
    projectId: 'elegantstyle-5b186',
    storageBucket: 'elegantstyle-5b186.firebasestorage.app',
    iosBundleId: 'com.example.elegantfaso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUrG7WsoldXB5feWoqpuVBgAwsTJMcQPk',
    appId: '1:152462835663:web:b07cdf9dd28aca1af81cba',
    messagingSenderId: '152462835663',
    projectId: 'elegantstyle-5b186',
    authDomain: 'elegantstyle-5b186.firebaseapp.com',
    storageBucket: 'elegantstyle-5b186.firebasestorage.app',
    measurementId: 'G-PNZ80GWS7B',
  );
}
